/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ProjetoCompras;

public class App {

    public static void main(String[] args){
areaCompras areacompras = new areaCompras();
areacompras.menu();
}
}